username: alexgoalie34@gmail.com
password: veqsy1-nuzxYz-biscyt
phone_number:

positions:
- Data Scientist
- Python Engineer
- Cyber Security
- Security Engineer, Penetration Testing
- Software Engineer
- Ruby Software Engineer

locations:
- Remote
- Dallas
- Chandler, Arizona

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
